print("keymaps.lua loaded") --
vim.cmd("command! W w") --equivalent to: vim.api.nvim_set_keymap('c', 'W', 'w', { noremap = true }), EXCEPT that in the latter, hitting :W actually displays :w, which it is effectively treated as

vim.keymap.set('n', '<leader>h', '<C-w>h', { desc = "move left window" })
vim.keymap.set('n', '<leader>H', '<C-w>H', { desc = "move current window to the left" })
vim.keymap.set('n', '<leader>j', '<C-w>j', { desc = "move down window" })
vim.keymap.set('n', '<leader>J', '<C-w>J', { desc = "move current window to the bottom" })
vim.keymap.set('n', '<leader>k', '<C-w>k', { desc = "move up window" })
vim.keymap.set('n', '<leader>K', '<C-w>K', { desc = "move current window to the top" })
vim.keymap.set('n', '<leader>l', '<C-w>l', { desc = "move right window" })
vim.keymap.set('n', '<leader>L', '<C-w>L', { desc = "move current window to the right" })
vim.keymap.set('n', '<leader>u', '<C-u>zz', { desc = "move up 1/2 page and recenter" })
vim.keymap.set('n', '<leader>d', '<C-d>zz', { desc = "move down 1/2 page and recenter" })
vim.keymap.set('n', '<leader>b', '<C-b>zz', { desc = "move up 1 page and recenter" })
vim.keymap.set('n', '<leader>f', '<C-f>zz', { desc = "move down 1 page and recenter" })
vim.keymap.set('n', '<Leader>ya', "mmggVG\"+y'mzz", { noremap = true, silent = true })
vim.keymap.set('n', '<Leader>yp', "mmvap\"+y'm", { noremap = true, silent = true })
vim.keymap.set('n', '<Leader>yy', "V\"+y", { noremap = true, silent = true })
vim.keymap.set('n', '<Leader>p', "\"+p", { noremap = true, silent = true })
vim.keymap.set('n', '<leader>r', function()
  vim.cmd("source ~/.config/nvim/init.lua")
  print("Sourced nvim init.lua config file")
end, { desc = "Reload nvim init.lua config" })
vim.keymap.set('n', '<leader>o', function() --useful for opening html files or other that can be viewed in the browser
  vim.cmd("!open %")
  print("Opened current file in browser")
end, { desc = "Open current file in browser" })
vim.keymap.set('n', 'ZA', ':xa<CR>', { desc = "quit and save all shortcut" })

-- Visual mode keymaps
vim.keymap.set('v', '<Leader>c', "\"+y", { noremap = true, silent = true })
vim.keymap.set('v', '<C-c>', "\"+y:lua vim.cmd('echo \"copied the following to clipboard: \" .. vim.fn.getreg('+') )'<CR><Esc>", { noremap = true, silent = true })
vim.keymap.set('v', '<Leader>p', "\"+p", { noremap = true, silent = true })
vim.keymap.set('v', '<C-v>', "\"+p", { noremap = true, silent = true })
vim.keymap.set('v', '<Leader>g', "\"+y:!open https://www.google.com/search?q=<C-r>+<CR><CR>", { noremap = true, silent = true })
vim.keymap.set('v', '<Leader>s', "\"+y:!open $(pbpaste)<CR><CR>", { noremap = true, silent = true })
